### ISSUE TITLE
How this app work?

### ISSUE THREAD

**Issue by tabacdenis** [seeker1983/python-gmail-attachment-processor#1]
Hi!
Thank you for this app!
Can you tell me how this work?

I need to extract file from emails from one specific email address. 
I need to indicate on load.py 

> gmail.load_unread('files', ['from_address@gmail.com'], "speciallabel") 

?

**Comment by seeker1983** [comment]
Yes, you're right.

Thats exactly what gmail.load_unread() does. Loads files from a list of chosen recipients(called whitelist) and saves in folder of first argument.

You can look at call example at [load.py](https://github.com/seeker1983/python-gmail-attachment-processor/blob/master/load.py), and description for load_unread in [gmail.py](https://github.com/seeker1983/python-gmail-attachment-processor/blob/master/gmail.py)

    gmail.load_unread(<FOLDER>, [<EMAIL1>, <EMAIL2>], "SOME_LABEL_TO_MARK_PROCESSED", <MARKASREAD:boolean>):

MARKASREAD:false might be used so processed emails will be processed on next run again(only unread emails would be processed)

after you setup credentials(might take a while if you don't have much experience with google projects), everything is pretty easy

**Comment by tabacdenis** [comment]
Thank you very much!

All work well.
